create table if not exists public.corner_ai_beta_applications (
  id bigint generated by default as identity primary key,
  email text not null,
  boxing_experience text not null check (boxing_experience in ('Just starting','< 6 months','6–12 months','1–3 years','3+ years')),
  solo_training_frequency text not null check (solo_training_frequency in ('Rarely','1x/week','2–3x/week','4+x/week')),
  device text not null check (device in ('iPhone','Android')),
  willingness_to_pay text not null check (willingness_to_pay in ('Yes','Maybe','No')),
  technique_issue text,
  traffic_source text,
  utm_source text,
  utm_medium text,
  utm_campaign text,
  utm_content text,
  utm_term text,
  referrer text,
  landing_url text,
  created_at timestamptz not null default now()
);

create unique index if not exists corner_ai_beta_applications_email_lower_idx
  on public.corner_ai_beta_applications (lower(email));

alter table public.corner_ai_beta_applications enable row level security;

drop policy if exists "anon can insert corner ai applications" on public.corner_ai_beta_applications;
create policy "anon can insert corner ai applications"
  on public.corner_ai_beta_applications
  for insert
  to anon
  with check (true);

create table if not exists public.corner_ai_validation_events (
  id bigint generated by default as identity primary key,
  event_name text not null check (event_name in ('page_view','demo_video_play','demo_video_complete','join_beta_click','form_start','form_submit')),
  session_id uuid not null,
  traffic_source text,
  utm_source text,
  utm_medium text,
  utm_campaign text,
  utm_content text,
  utm_term text,
  referrer text,
  landing_url text,
  path text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists corner_ai_validation_events_event_created_idx
  on public.corner_ai_validation_events (event_name, created_at desc);
create index if not exists corner_ai_validation_events_session_idx
  on public.corner_ai_validation_events (session_id);

alter table public.corner_ai_validation_events enable row level security;

drop policy if exists "anon can insert corner ai events" on public.corner_ai_validation_events;
create policy "anon can insert corner ai events"
  on public.corner_ai_validation_events
  for insert
  to anon
  with check (true);

revoke all privileges on table public.corner_ai_beta_applications from anon, authenticated;
revoke all privileges on table public.corner_ai_validation_events from anon, authenticated;

grant insert on table public.corner_ai_beta_applications to anon;
grant insert on table public.corner_ai_validation_events to anon;
grant usage on sequence public.corner_ai_beta_applications_id_seq to anon;
grant usage on sequence public.corner_ai_validation_events_id_seq to anon;
